import Header from "@/components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create note | MyNotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header >
        <Header />
      </header>

      <main>
        {children}
      </main>
    </>
  );
}
